ALTER TABLE users ALTER COLUMN firstname SET NOT NULL,ALTER COLUMN lastname SET NOT NULL, ALTER COLUMN user_email SET NOT NULL, ALTER COLUMN user_password SET NOT NULL;
ALTER TABLE products ALTER COLUMN productname SET NOT NULL,ALTER COLUMN price SET NOT NULL, ALTER COLUMN category SET NOT NULL;
ALTER TABLE orders ALTER COLUMN user_id SET NOT NULL,ALTER COLUMN status SET NOT NULL;
ALTER TABLE order_product ALTER COLUMN order_id SET NOT NULL,ALTER COLUMN product_id SET NOT NULL, ALTER COLUMN quantity SET NOT NULL;
